### ISSUE TITLE
Retrieval of 36-10-0608-01

### ISSUE THREAD

**Issue by PhilSmith26** [mountainMath/cansim#107]
While retrieving this cansim table it kept parsing for over an hour. When done, the following warning messages appeared:

Accessing CANSIM NDM product 36-10-0608 from Statistics Canada
Parsing data
Warning messages:                                                                                                
1: In value[[3L]](cond) :
  Could not convert field Prices to a factor, please flag this as an issue in the {cansim} repository at https://github.com/mountainMath/cansim/issues.
2: In value[[3L]](cond) :
  Could not convert field Purchasing industry to a factor, please flag this as an issue in the {cansim} repository at https://github.com/mountainMath/cansim/issues.
3: In value[[3L]](cond) :
  Could not convert field Asset to a factor, please flag this as an issue in the {cansim} repository at https://github.com/mountainMath/cansim/issues.
4: In value[[3L]](cond) :
  Could not convert field Asset function to a factor, please flag this as an issue in the {cansim} repository at https://github.com/mountainMath/cansim/issues.

**Comment by mountainMath** [comment]
Thanks for flagging, will look into what goes wrong there. For now, you can suppress the warning messages by passing the `factors="FALSE"` argument to `get_cansim`. This is a rather large table, it's 500Mb when compressed, which is why it takes quite some time to parse the data and add the metadata. One way to speed this up is to use `get_cansim_sqlite` instead, which stores the data in an sqlite on disk (in a permanent location if the cansim.cache_path option is set or the cache path is explicitly provided). That eliminates the need for re-downloading the data across sessions, and also enables to do database level filtering before extracting and normalizing the data for more efficient memory use and faster parsing. The initial download and indexing of the database will still take some time though.

**Comment by mountainMath** [comment]
Also, which version of the cansim package are you using? I just tried running it normally and did not get the warning messages you got? I am on R 4.2 and cansim 0.3.11 on MacOS 12.4.

**Comment by PhilSmith26** [comment]
There is no problem on my end. The table came down despite the warnings.

R version 4.1.1, cansim 0.3.10, MacOS 12.4

Philip

**Comment by mountainMath** [comment]
This should be fixed in the current CRAN version.
