### ISSUE TITLE
Provide access to PUMF files via package

### ISSUE THREAD

**Issue by hswerdfe** [mountainMath/cansim#117]
I only saw on mention of PUMF in past issues to I am just proposing this:

Labour Force Survey: Public Use Microdata File is released every week or so.

It would be good if the cansim package had a function to get the PUMF similar to the get_cansim function.

web link to the surveys main webpage
https://www150.statcan.gc.ca/n1/en/catalogue/71M0001X

web link to the surveys latest download page
https://www150.statcan.gc.ca/n1/pub/71m0001x/71m0001x2021001-eng.htm

direct links to the latest (as of today) PUMF file for this survey.

https://www150.statcan.gc.ca/n1/pub/71m0001x/2021001/2023-05-CSV.zip
https://www150.statcan.gc.ca/n1/en/pub/71m0001x/2021001/2023-05-PRN.zip?st=bqdhNcsH

I propose an interface something like 

This function might return the most recent csv file as a data frame.
get_pumf(pumf_id = ''71M0001X')

This function might return a list of dates available for the this PUMF
get_pumf_dates(pumf_id = ''71M0001X') 

This could return a specific dated version of the the file.
get_pumf(pumf_id = ''71M0001X', date = '2023-05')

**Comment by mountainMath** [comment]
For pumf files I have started on a [separate package](https://github.com/mountainMath/canpumf) to download pumf files, parse the metadata and fold it in. The package is a bit of a mess right now because my initial idea of having uniform scripts to parse the metadata did not pan out due to the large variation of how StatCan codes the metadata, even across different releases of the same survey.

That said, the LFS is an exception in that their pumf data has been uniformly coded ([with minor exceptions](https://github.com/mountainMath/canpumf/issues/6)). But everything broke after the recent revamp of the LFS, and this needs fixing. Haven't yet found the time to do this though.

**Comment by mountainMath** [comment]
The canpumf package has been updated to work with the new LFS data (and some other pumf data. Still believe it's better to have this in a separate package, coming this issue.
