### ISSUE TITLE
Issues pulling data from Statistics Canada's Table 20-10-0056-01

### ISSUE THREAD

**Issue by chrisferris3** [mountainMath/cansim#119]
Not sure if this is a cansim thing, or a Stats Canada thing, but I keep getting this message when I try to pull data from this table using a few different cansim package methods. I think it is likely a Stats Canada issue. I have been trying to figure out how to work around this.

Warning message:
In value[[3L]](cond) :
  There is inconsitent naming of categories in column Sales, cannot convert to factors.
This is likely a problem with StatCan data, proceed with caution when filtering on this field
to ensure data integrity. If this turns out to be a problem with the {cansim} package rather
than with StatCan, or if this problem can't be resolved, please flag this as an issue in the
{cansim} repository at https://github.com/mountainMath/cansim/issues

**Comment by mountainMath** [comment]
Thanks for flagging, this is an issue with the package. It got confused by the order in the metadata for this table being mixed up, for the `Sales` and `Adjustments` columns. And messes up folding in the metadata as a result and can't convert to factors as it usually would. There should be no impact on usage if you don't use the `Hierarchy` or `Classification Code` information in your workflow for this table. Scheduling this to get fixed in the next version.

<img width="657" alt="image" src="https://github.com/mountainMath/cansim/assets/1395960/af5a766d-2123-4c68-8871-166be6d26714">

**Comment by mountainMath** [comment]
Fixed in the current development branch https://github.com/mountainMath/cansim/tree/v0.3.16 and scheduled for next release in https://github.com/mountainMath/cansim/pull/120.

**Comment by chrisferris3** [comment]
Thank you!!!!!

**Comment by chrisferris3** [comment]
I got it to work with this bit of code.
install.packages("remotes")
library(remotes)

# this is for mountainMath/cansim/tree/v0.3.16  --- ###
remotes::install_github("mountainmath/cansim", 
                        ref= github_pull("120"),
                        force = TRUE)
