### ISSUE TITLE
Purpose of adjust_cansim_values_by_variable function

### ISSUE THREAD

**Issue by dshkol** [mountainMath/cansim#23]
I'm not sure what this function is meant to do, and its parameters are undocumented.

```r
#' (Legacy function) Adjust CANSIM table values by scaled amount; however 
#' French does not work, probably due to encoding issues.
#' 
#' @param data ???
#' @param var ???
#' 
#' @export
adjust_cansim_values_by_variable <-function(data,var){
  normalize_cansim_values(data)
}
```

If I'm reading it right, what's the point of this given it's just a call to `normalize_cansim_values`, and the  `var` parameter isn't used for anything, and this function isn't called anywhere else.

**Comment by mountainMath** [comment]
I left it in there because it gets called by some of my old "reproducible" posts. But the change in column names breaks reproducibility anyway. Not sure what to do. Maybe leave it and just output an error message that people should replace it with the other function name? In the new NDM we don't need to specify the variable any more.

**Comment by mountainMath** [comment]
Or just trow it out. It's probably only my blog post and some old snippets I have that have used this.

**Comment by dshkol** [comment]
We can soft deprecate it and leave it in, but you should still define the parameters - and is the `var` parameter even used here?

**Comment by mountainMath** [comment]
Not used any more, but it was part of the original function. So code will still have a parameter in there.
