### ISSUE TITLE
Can't download the latest data for "Labour Force Survey (LFS)" on LFS morning

### ISSUE THREAD

**Issue by biswask** [mountainMath/cansim#50]
Hello,
I tried to download CANSIM data 2820001, 2820087, 2820088, 2820089, 2820122 and 2820135 this morning using CANSIM package. The data was downloaded but the latest month (i.e. October) data was not there (It's not working till now). However when I tried to download Cansim#2820083  in the morning (using the same package and same code), it was downloaded perfectly with the current month. So far this package is perfectly working for other releases such as  Employment Insurance, or Job vacancy Wage Survey. I don't know why it is not working for Labour Force Survey. Can you please advise?

Thanks in advance,
Keya.

**Comment by mountainMath** [comment]
When I check the October data seems to be there. Either it was added later today or you ran into caching issues. The package caches the data locally for the duration of the session in order to speed up processing and reduce network traffic. If you had your session open and already requested the table the day before, it will just hit the cache. To avoid that, either restart your session or pass in the `refresh=TRUE` option like
```
cansim::get_cansim("2820001",refresh = TRUE)
```
to make sure you get the latest data. We should probably take it clear in the messages in each call whether we access the data from the cache or download it from StatCan.
