### ISSUE TITLE
get_cansim_vector has stopped working

### ISSUE THREAD

**Issue by t-hind** [mountainMath/cansim#67]
I was just just trying to download some vectors from stats can and there seems to be a problem with get_cansim_vector. Running the code even when pulling only 1 vector gives the same error.

> get_cansim_vector("v41690973","2015-01-01")
Error in get_cansim_vector_for_latest_periods(vectors, periods = 10000) : 
  Problem downloading data, status code 416
The number of object in the list exceeds the limit - 6000. Error code = 9

I did run get_cansim("14-10-0320-01") which pulled the data perfect fine just as a check to see if it was an issue with my computer.

**Comment by t-hind** [comment]
Update, I found the issue. When I examined the base code I found the problem. If use_ref_date = TRUE (the default) then the code below runs. It seems like Stats Can's API has lowered the max number of periods that can be pulled at once to 6000 (down from 10000 which was used before). 

result <- get_cansim_vector_for_latest_periods(vectors, 
            periods = 10000) %>% filter(as.Date(.data$REF_DATE) >= 
            start_time, as.Date(.data$REF_DATE) <= end_time)

Change the above periods argument to 6000 (or lower depending on how the API reacts) should fix this problem.

If the use_ref_date = FALSE, then code works as you would expect with no issues.

**Comment by pollytatouin** [comment]
I am running into the same issue. t-hind's fix does work, though it seems like now downloading more than one series at a time is impossible. I seem to remember that we could do so in the past, as hinted by the "vectorS" argument of the `get_cansim_vector` function.

``` r
require(cansim)
#> Loading required package: cansim
require(dplyr)
#> Loading required package: dplyr
#> Warning: package 'dplyr' was built under R version 3.4.4
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

new_get_cansim_vector <- function(vectors, start_time, end_time = Sys.Date(), use_ref_date = TRUE){
  start_time = as.Date(start_time)
  end_time = as.Date(end_time)
  if (!use_ref_date) {
    time_format = "%Y-%m-%dT%H:%m"
    vectors = gsub("^v", "", vectors)
    url = "https://www150.statcan.gc.ca/t1/wds/rest/getBulkVectorDataByRange"
    vectors_string = paste0("\"vectorIds\":[", paste(purrr::map(as.character(vectors), 
                                                                function(x) paste0("\"", x, "\"")), collapse = ", "), 
                            "]")
    time_string = paste0("\"startDataPointReleaseDate\": \"", 
                         strftime(start_time, time_format), "\",\"endDataPointReleaseDate\": \"", 
                         strftime(end_time, time_format), "\"")
    response <- post_with_timeout_retry(url, body = paste0("{", 
                                                           vectors_string, ",", time_string, "}"))
    if (is.null(response)) 
      return(response)
    if (response$status_code != 200) {
      stop("Problem downloading data, status code ", response$status_code, 
           "\n", httr::content(response))
    }
    data <- httr::content(response)
    data1 <- Filter(function(x) x$status == "SUCCESS", data)
    data2 <- Filter(function(x) x$status != "SUCCESS", data)
    if (length(data2) > 0) {
      message(paste0("Failed to load data for ", length(data2), 
                     " vector(s)."))
      data2 %>% purrr::map(function(x) {
        message(paste0("Problem downloading data: ", 
                       response_status_code_translation[as.character(x$object$responseStatusCode)]))
      })
    }
    if (length(data1) > 0) 
      result <- extract_vector_data(data1) %>% rename_vectors(vectors)
    else result <- tibble::tibble()
  }
  else {
    result <- get_cansim_vector_for_latest_periods(vectors, 
                                                   periods = 6000) %>% filter(as.Date(.data$REF_DATE) >= 
                                                                                start_time, as.Date(.data$REF_DATE) <= end_time)
  }
  result
}

# Works
new_get_cansim_vector("v1", start_time = "1900-01-01")
#> # A tibble: 294 x 9
#>    DECIMALS  VALUE REF_DATE releaseTime SYMBOL frequencyCode SCALAR_ID
#>       <int>  <dbl> <chr>    <chr>        <int>         <int>     <int>
#>  1        0 1.22e7 1946-01~ 2000-02-18~      0             9         0
#>  2        0 1.22e7 1946-04~ 2000-02-18~      0             9         0
#>  3        0 1.23e7 1946-07~ 2000-02-18~      0             9         0
#>  4        0 1.24e7 1946-10~ 2000-02-18~      0             9         0
#>  5        0 1.25e7 1947-01~ 2000-02-18~      0             9         0
#>  6        0 1.25e7 1947-04~ 2000-02-18~      0             9         0
#>  7        0 1.26e7 1947-07~ 2000-02-18~      0             9         0
#>  8        0 1.26e7 1947-10~ 2000-02-18~      0             9         0
#>  9        0 1.27e7 1948-01~ 2000-02-18~      0             9         0
#> 10        0 1.28e7 1948-04~ 2000-02-18~      0             9         0
#> # ... with 284 more rows, and 2 more variables: COORDINATE <chr>,
#> #   VECTOR <chr>
new_get_cansim_vector("v62", start_time = "1900-01-01")
#> # A tibble: 293 x 9
#>    DECIMALS VALUE REF_DATE releaseTime SYMBOL frequencyCode SCALAR_ID
#>       <int> <dbl> <chr>    <chr>        <int>         <int>     <int>
#>  1        0 73273 1946-01~ 2000-02-18~      0             9         0
#>  2        0 86530 1946-04~ 2000-02-18~      0             9         0
#>  3        0 88465 1946-07~ 2000-02-18~      0             9         0
#>  4        0 83203 1946-10~ 2000-02-18~      0             9         0
#>  5        0 89319 1947-01~ 2000-02-18~      0             9         0
#>  6        0 96722 1947-04~ 2000-02-18~      0             9         0
#>  7        0 91900 1947-07~ 2000-02-18~      0             9         0
#>  8        0 82002 1947-10~ 2000-02-18~      0             9         0
#>  9        0 85176 1948-01~ 2000-02-18~      0             9         0
#> 10        0 89996 1948-04~ 2000-02-18~      0             9         0
#> # ... with 283 more rows, and 2 more variables: COORDINATE <chr>,
#> #   VECTOR <chr>

# Fails
try(new_get_cansim_vector(list("v1", "v62"), start_time = "1900-01-01"))
#> Error in get_cansim_vector_for_latest_periods(vectors, periods = 6000) : 
#>   Problem downloading data, status code 416
#> The number of object in the list exceeds the limit - 6000. Error code = 9
try(new_get_cansim_vector(c("v1", "v62"), start_time = "1900-01-01"))
#> Got timeout from StatCan, trying again
#> Error in get_cansim_vector_for_latest_periods(vectors, periods = 6000) : 
#>   Problem downloading data, status code 416
#> The number of object in the list exceeds the limit - 6000. Error code = 9

try(new_get_cansim_vector(list("v1", "v62"), start_time = "2017-01-01"))
#> Error in get_cansim_vector_for_latest_periods(vectors, periods = 6000) : 
#>   Problem downloading data, status code 416
#> The number of object in the list exceeds the limit - 6000. Error code = 9
```

<sup>Created on 2019-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by t-hind** [comment]
I would suggest changing the function to include a period option with it being year, month, week, or day to fill into the lubridate's time_length variable. This means you will have the number of periods called change depending on how many periods there are. Since you can only download 6000 rows of data now in TOTAL having that be a fixed number runs into a lot of problems.

The new function would be below.

new_get_cansim_vector <- function(vectors, start_time, end_time = Sys.Date(), use_ref_date = TRUE, period = "month"){
  start_time = as.Date(start_time)
  end_time = as.Date(end_time)
  if (!use_ref_date) {
    time_format = "%Y-%m-%dT%H:%m"
    vectors = gsub("^v", "", vectors)
    url = "https://www150.statcan.gc.ca/t1/wds/rest/getBulkVectorDataByRange"
    vectors_string = paste0("\"vectorIds\":[", paste(purrr::map(as.character(vectors), 
                                                                function(x) paste0("\"", x, "\"")), collapse = ", "), 
                            "]")
    time_string = paste0("\"startDataPointReleaseDate\": \"", 
                         strftime(start_time, time_format), "\",\"endDataPointReleaseDate\": \"", 
                         strftime(end_time, time_format), "\"")
    response <- post_with_timeout_retry(url, body = paste0("{", 
                                                           vectors_string, ",", time_string, "}"))
    if (is.null(response)) 
      return(response)
    if (response$status_code != 200) {
      stop("Problem downloading data, status code ", response$status_code, 
           "\n", httr::content(response))
    }
    data <- httr::content(response)
    data1 <- Filter(function(x) x$status == "SUCCESS", data)
    data2 <- Filter(function(x) x$status != "SUCCESS", data)
    if (length(data2) > 0) {
      message(paste0("Failed to load data for ", length(data2), 
                     " vector(s)."))
      data2 %>% purrr::map(function(x) {
        message(paste0("Problem downloading data: ", 
                       response_status_code_translation[as.character(x$object$responseStatusCode)]))
      })
    }
    if (length(data1) > 0) 
      result <- extract_vector_data(data1) %>% rename_vectors(vectors)
    else result <- tibble::tibble()
  }
  else {
    # n finds the number of periods (the default is months) to call with the get_cansim_vector_for_latest_periods function. This would change depending on how many months you are calling, so it you are only looking at a year you call pull more vectors at once.
    n <- round(lubridate::time_length(end_time - as.Date(start_time), unit = period), digits = 0) + 1 
    result <- get_cansim_vector_for_latest_periods(vectors, 
                                                   periods = n) %>% filter(as.Date(.data$REF_DATE) >= 
                                                                             start_time, as.Date(.data$REF_DATE) <= end_time)
  }
  result
}

# still works
new_get_cansim_vector("v62", start_time = "1900-01-01")


# These now work since they are pull less than 6000 rows for each vector call. The number of vectors you can pull at once is still significantly less than it was before
try(new_get_cansim_vector(list("v1", "v62"), start_time = "1900-01-01"))

try(new_get_cansim_vector(c("v1", "v62"), start_time = "1900-01-01"))

try(new_get_cansim_vector(list("v1", "v62"), start_time = "2017-01-01"))

**Comment by pollytatouin** [comment]
What is weird though is that v1 and v62 together are far from summing to 6000 rows, not even 6000 cells. So I'm not quite sure where the bug is.

You suggestion is interesting, although it requires setting a "period" or "frequency" argument, which makes the whole thing much less convenient. In particular, setting this argument for a list of vectors with different frequencies would be cumbersome. 

I'll keep thinking about it. Might be worth email Statcan to complain about it.

**Comment by t-hind** [comment]
Oh I totally agree that setting a "period" or "frequency" argument, is far from ideal I just noticed that it seems to be the number of periods called in total is the limiting factor regardless of the number of observations each series has. This was my work around in the short term to still call multiple vectors at once (which is now significantly more difficult to do)

**Comment by mountainMath** [comment]
Thanks for the info, will look into this tomorrow. The 6000 limit is imposed by StatCan. It could be solved with pagination, but that requires work. Especially since it's hard to know ahead of time how many rows a request will try to access.

The `use_ref_date` option defaults to `TRUE` because most people expect to query data by REF_DATE, but StatCan APIs only allow to access by date updated, which could be significantly later. So people were getting data not as far back as they expected.

The call to using `get_cansim_vector_for_latest_periods` served as a workaround to simply download all data and then cut internally. But that's less than ideal. I will check with StatCan if they can add another API call to facilitate this.

It appears that the `get_cansim_vector_for_latest_periods` also broke the ability to get data for several vectors.

**Comment by pollytatouin** [comment]
I guess another workaround would be to send one request of 6000 periods per vector id, collect all the outputs, and concatenate a posteriori ?

**Comment by pollytatouin** [comment]
Here's an example (forced me to finally look into `purrr`: yeah!)

``` r

require(cansim)
#> Loading required package: cansim
require(dplyr)
#> Loading required package: dplyr
#> Warning: package 'dplyr' was built under R version 3.4.4
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
require(purrr)
#> Loading required package: purrr
#> Warning: package 'purrr' was built under R version 3.4.4

vectors <- c(1, 2)

new_get_cansim_vector_for_latest_periods <- function (vectors, periods = 1){
  vectors = gsub("^v", "", vectors)
  url = "https://www150.statcan.gc.ca/t1/wds/rest/getDataFromVectorsAndLatestNPeriods"
  vectors_string = paste0("[", paste(purrr::map(as.character(vectors), 
                                                function(x) paste0("{\"vectorId\":", x, ",\"latestN\":", 
                                                                   periods, "}")), collapse = ", "), "]")
  response <- cansim:::post_with_timeout_retry(url, body = vectors_string)
  if (is.null(response)) 
    return(response)
  if (response$status_code != 200) {
    stop("Problem downloading data, status code ", response$status_code, 
         "\n", httr::content(response))
  }
  data <- httr::content(response)
  data1 <- Filter(function(x) x$status == "SUCCESS", data)
  data2 <- Filter(function(x) x$status != "SUCCESS", data)
  if (length(data2) > 0) {
    message(paste0("Failed to load data for ", length(data2), 
                   " vector(s)."))
    data2 %>% purrr::map(function(x) {
      message(paste0("Problem downloading data: ", response_status_code_translation[as.character(x$object$responseStatusCode)]))
    })
  }
  if (length(data1) > 0){
    result <- cansim:::extract_vector_data(data1) %>% cansim:::rename_vectors(vectors)
  } else {
    result <- tibble::tibble()
  }
  
  result
}

out <- map(vectors, new_get_cansim_vector_for_latest_periods, periods = 6000)

bind_rows(out)
#> # A tibble: 566 x 9
#>    DECIMALS  VALUE REF_DATE releaseTime SYMBOL frequencyCode SCALAR_ID
#>       <int>  <dbl> <chr>    <chr>        <int>         <int>     <int>
#>  1        0 1.22e7 1946-01~ 2000-02-18~      0             9         0
#>  2        0 1.22e7 1946-04~ 2000-02-18~      0             9         0
#>  3        0 1.23e7 1946-07~ 2000-02-18~      0             9         0
#>  4        0 1.24e7 1946-10~ 2000-02-18~      0             9         0
#>  5        0 1.25e7 1947-01~ 2000-02-18~      0             9         0
#>  6        0 1.25e7 1947-04~ 2000-02-18~      0             9         0
#>  7        0 1.26e7 1947-07~ 2000-02-18~      0             9         0
#>  8        0 1.26e7 1947-10~ 2000-02-18~      0             9         0
#>  9        0 1.27e7 1948-01~ 2000-02-18~      0             9         0
#> 10        0 1.28e7 1948-04~ 2000-02-18~      0             9         0
#> # ... with 556 more rows, and 2 more variables: COORDINATE <chr>,
#> #   VECTOR <chr>
```

<sup>Created on 2019-08-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pollytatouin** [comment]
This would also require a `sys.sleep(1)` function in the code to avoid getting timed out if we request several vectors (the function would fail for me every time I requested more than two series).

**Comment by mountainMath** [comment]
Just got around to taking a look at this issue. It strikes me that

a) The problem arises because StatCan API does not allow querying by REF_DATE, only by data the entry was last updated. After feedback from users of `cansim`, who overwhelmingly are looking to search by REF_DATE, we added the `use_ref_date` option to the `get_cansim_vector` and set the default value to `TRUE`, which under the hood uses the `get_cansim_vector_for_latest_periods` function to request all data points for the vector and filters it back down by REF_DATE.

This is a less than ideal workaround and would be best solved by StatCan adding an API endpoint to achieve this directly. I will contact StatCan and see if this can be done.

b) This problem suddenly became urgent (and broke the package) because StatCan changed the maximum allowable vectors to download down to 6000, and they don't check the actual number of rows that will be returned but reject any call asking for more than 6000 entries. 

c) As a fix I am now capping the requested periods so that the total number of rows requested is below the 6000 cutoff, and issue a warning if more periods were requested in the https://github.com/mountainMath/cansim/tree/row-limit branch. This might run into problems when requesting a lot of data, in which case for now the user would have to do multiple calls. Multiple calls will significantly slow down the code.

d) In the medium term it might be useful to implement a way to more gracefully deal with the issue around the maximum number of rows.

e) For users that consume a lot of data as indicated above it might be best to use the `get_cansim_vector` with the `use_ref_date=FALSE` option to update data that is stored locally. It might be useful to add functionality that does exactly that in the future.

**Comment by mountainMath** [comment]
The branch can be installed via
`remotes::install_github("mountainmath/cansim@row-limit")`

**Comment by mountainMath** [comment]
It also occurs to me that the internal workflow in the package can be simplified. It should be safe to assume that `REF_DATE` is always less than or equal to the `ReleaseDate`, so there is no need to fall back to the `get_cansim_vector_for_latest_periods` function. I will experiment with this and switch the code over. That would simplify things further.

**Comment by mountainMath** [comment]
Did some more fine-tuning and getting ready for CRAN update. Would be great if @pollytatouin or @t-hind could give this a test run. Install via:
```
remotes::install_github("mountainmath/cansim@use-ref-date")
```
This restores normal functionality, but still fails when running into 6000 row limit. Hoping to get StatCan to implement pagination logic in their calls so we can iterate over this. Right now there is for example no straight-forward way to even just get the last month worth of CPI data. Taking all 2101 available CPI vectors as a starting point
```
cpi_data <- get_cansim("18-10-0004") 
vectors <- unique(cpi_data$VECTOR)
```
and attempting to get data for 2019-05 by date still fails:
```
cpi_vector_data <- get_cansim_vector(vectors,start_time = "2019-05-01",end_time = "2019-05-01") 
```
This is because we are trying to search by REF_DATE, and the call loads all data with a release data on or after "2019-05-01" and then cuts down internally. But more than 6000 rows have been released since this date. Knowing that 2019-05 is the second last released data (as of right now) we can download the data via
```
get_cansim_vector_for_latest_periods(vectors=vectors,periods=2) 
  %>% filter(REF_DATE=="2019-05-01") 
```
This method will fail once the data for 2019-07 comes in.

A more robust method is by splitting up the request into smaller groups of vectors at a time
```
cpi_vector_data <- batch::msplit(vectors,20) %>%
  purrr::map(function(vs){
    Sys.sleep(1)
    get_cansim_vector(vectors=unlist(vs),start_time = "2019-05-01",end_time = "2019-05-01")
    }) %>% 
  bind_rows()
```

This last method can be adapted to work with any kind of request by changing the number of batches.

**Comment by pollytatouin** [comment]
Thank you for looking into this. I’m away from my computer today, but will give it a try over the weekend.

**Comment by t-hind** [comment]
Thanks for this! I looked at it quickly last night and I will try to get to it this afternoon/tomorrow if possible

**Comment by pollytatouin** [comment]
Hi @mountainMath . Finally got the time to test the new branch and everything seems to be working just fine. The simplifications you've brought look very good (e.g. relying less on "latestNperiod" and exploiting the fact that if end_time=Sys.Date() then you retrieve data up to the most recent point anyway).

Thank you for the great support.

**Comment by mountainMath** [comment]
Thanks. It's on its way to CRAN. Should be live within the next couple of days.
