### ISSUE TITLE
Recent month data is not coming

### ISSUE THREAD

**Issue by biswask** [mountainMath/cansim#71]
Good morning!

I was trying to download the data 14-10-0288-01 from Statistics Canada's website this morning using the following code:

d=get_cansim("14-10-0288-01", refresh = TRUE, timeout=1000)

The recent month's data came after 1 hour of data release. But we need the data within 15 minutes after the data came out. Is there anything you can do to speed up the process? 

Last month I faced the same problem. The December data started downloading after 3 hours of LFS data released by Stat Can.

However, when I download the data using coordinate, the is no problem of downloading the recent months data. But I need to download the whole dataset. Any help will be much appreciated.

Thanks,
Keya.

**Comment by mountainMath** [comment]
Last month the issue was with StatCan not updating the tables in a timely fashion. Might have been similar this time, did not check. StatCan advised last month that pulling vector data will result in the up-to-date data, whereas downloading tables had problems. Hopefully those problems will get reduced as StatCan works out the kinks in the system at their end.

**Comment by biswask** [comment]
Thanks for the response....
